// Copyright The Rusted Firmware-A Contributors.
//
// SPDX-License-Identifier: BSD-3-Clause

//! Trace Buffer Extension
//! The TRBE is a trace buffer unit that stores trace generated by a trace unit into system memory.
//! For example, a TRBE could capture trace generated by a trace unit for a particular PE.
//!
//! The trace buffer has the following characteristics:
//!
//! - Can be physically or virtually addressed (normally virtually addressed).
//! - Has an owning translation regime.
//! - Is defined by pointer registers.
//! - Its operation is affected by external events like triggers.

use super::CpuExtension;

use crate::context::{CpuContext, World};

use arm_sysregs::{IdAa64dfr0El1, MdcrEl3, read_id_aa64dfr0_el1};

pub struct TraceBuffer;

impl TraceBuffer {
    fn enable_ns(ctx: &mut CpuContext) {
        ctx.el3_state.mdcr_el3 |= MdcrEl3::NSTB_EN | MdcrEl3::NSTB_SS;
        ctx.el3_state.mdcr_el3 -= MdcrEl3::NSTBE;
    }

    fn disable_all(world: World, ctx: &mut CpuContext) {
        ctx.el3_state.mdcr_el3 -= MdcrEl3::NSTB_EN | MdcrEl3::NSTBE;

        match world {
            World::NonSecure => {
                ctx.el3_state.mdcr_el3 -= MdcrEl3::NSTB_SS;
            }
            World::Secure => {
                ctx.el3_state.mdcr_el3 |= MdcrEl3::NSTB_SS;
            }
            #[cfg(feature = "rme")]
            World::Realm => {
                ctx.el3_state.mdcr_el3 |= MdcrEl3::NSTB_SS;
            }
        }
    }
}

impl CpuExtension for TraceBuffer {
    fn is_present(&self) -> bool {
        !(read_id_aa64dfr0_el1() & IdAa64dfr0El1::TRACE_BUFFER_MASK).is_empty()
    }

    fn configure_per_cpu(&self, world: World, ctx: &mut CpuContext) {
        match world {
            World::NonSecure => {
                // TODO: core affected disable?
                // Self::disable_all(ctx, true);
                Self::enable_ns(ctx);
            }
            World::Secure => {
                Self::disable_all(world, ctx);
            }
            #[cfg(feature = "rme")]
            World::Realm => {
                Self::disable_all(world, ctx);
            }
        }
    }
}
