# Copyright The Rusted Firmware-A Contributors.
#
# SPDX-License-Identifier: BSD-3-Clause

[package]
description = "Arm Granule Protection Library"
name = "arm-gpt"
version = "0.1.0"
edition = "2024"
authors = ["Ludovic Mermod <ludovic.mermod@arm.com>"]
license = "MIT OR Apache-2.0"
repository = "https://git.trustedfirmware.org/arm-firmware-crates/arm-gpt.git"
keywords = ["arm", "memory", "security", "driver"]
categories = ["hardware-support", "embedded", "no-std", "no-std::no-alloc"]
readme = "README.md"


[dependencies]
num_enum = { version = "0.7.4", default-features = false }
zerocopy = { version = "0.8.26", features = ["derive"] }
thiserror = { version = "2.0", default-features = false }
spin = { version = "0.10.0", default-features = false, features = [
    "lazy",
    "once",
    "spin_mutex",
] }
paste = "1.0.14"

[target.'cfg(target_arch = "aarch64")'.dependencies]
arm-sysregs = { version = "0.1.0", path = "../arm-sysregs", features = ["rme"] }
